### ISSUE TITLE
Use of ESP32 ULP mode?

### ISSUE THREAD

**Issue by papadeltasierra** [francescovannini/espmeter#3]
Ref: https://github.com/espressif/esp-idf/tree/ac99c0ad6b/examples/system/ulp_fsm/ulp
Have you considered trying an ESP32 and using ULP mode?  If I read the specs correctly, your Tiny13 and sleeping ESP8266 will be using 5+15microA but the ULP on an ESP32 could do the counting job using just 16microA.  Appreciate that the ESP32 probably wasn't around when you first did this so "respect" for getting this to work on such low power!

**Comment by francescovannini** [comment]
Thanks for the tip. I indeed didn't consider the ESP32 mainly because I had some spare 8266 at the time, waiting to be put to use. The values you indicated are correct, the difference between my setup and using an ESP32 is probably in the order of 5-10uA. I think what makes the real difference is the power consumption of the ESP32 vs 8266 when in use, even if for a brief period, as it could offset that difference when sleeping. According to [this](https://blog.voneicken.com/2018/lp-wifi-esp-comparison/) the power consumption is very similar when using a secured AP, while the 8266 performs much better when using an insecure AP; this is expected, as the ESP32 is computationally more capable; however, for this specific application, we hardly need to have a multi-core processor.

In fact, if the objective is to prolong the battery life even further, I would experiment with a slightly different setup: an ATTiny85 that powers up (from shutdown, not deep sleep) the ESP8266. The Tiny85 power consumption is similar to the Tiny13 while in deep sleep, but it has 8 times the RAM; this would allow to store an entire day of samples without the need to use the 8266 RTC memory. In this setup, the consumption would be most of the time just 5uA.

**Comment by papadeltasierra** [comment]
Wow, that's an interesting idea.  I have an ESP8266 somewhere so maybe I'll give that a go.
